name: Build

on:
  push:
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove old files and folders
        run: |
          rm -rf package-lock.json
          rm -rf dist
          rm -rf *.vsix
      - name: install node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM
        run: npm install
      - name: Compile vsix package
        run: |
          npm run build
          npm run package

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: install node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM
        run: npm install
      - name: Build and Package
        run: |
          npm run build
          npm run package
      - name: Publish to VS Code Marketplace
        run: npx vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
